import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { Detection } from "@/components/SpeciesResults";

interface ExportOptions {
  detections: Detection[];
  latitude?: string;
  longitude?: string;
  recordedDate?: string;
  recordedBy?: string;
}

function buildMetaXml(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" linesTerminatedBy="\\n" fieldsTerminatedBy="\\t" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>occurrence.txt</location>
    </files>
    <id index="0"/>
    <field index="1" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/vernacularName"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/decimalLatitude"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/decimalLongitude"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/identificationRemarks"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/occurrenceRemarks"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/associatedMedia"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/vernacularName" default=""/>
  </core>
</archive>`;
}

function buildEmlXml(options: ExportOptions): string {
  const now = new Date().toISOString().split("T")[0];
  return `<?xml version="1.0" encoding="UTF-8"?>
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd"
         packageId="lkotkote-export-${now}" system="http://gbif.org" scope="system">
  <dataset>
    <title>Lkotkote Bioacoustic Survey</title>
    <creator>
      <individualName>
        <givenName>${options.recordedBy || "Lkotkote User"}</givenName>
      </individualName>
    </creator>
    <pubDate>${now}</pubDate>
    <abstract>
      <para>Bird species detections from bioacoustic analysis combined with Traditional Ecological Knowledge (TEK) annotations. Generated by Lkotkote platform.</para>
    </abstract>
    <intellectualRights>
      <para>This work is licensed under a Creative Commons Attribution 4.0 International License.</para>
    </intellectualRights>
  </dataset>
</eml:eml>`;
}

function buildOccurrenceTsv(options: ExportOptions): string {
  const header = [
    "occurrenceID",
    "basisOfRecord",
    "scientificName",
    "vernacularName",
    "eventDate",
    "decimalLatitude",
    "decimalLongitude",
    "recordedBy",
    "identificationRemarks",
    "occurrenceRemarks",
    "associatedMedia",
  ].join("\t");

  const rows = options.detections.map((d) => {
    const confidence = `BirdNET confidence: ${(d.confidence * 100).toFixed(1)}%`;
    const tek = d.tekAnnotation || "";
    return [
      d.id,
      "MachineObservation",
      d.species,
      d.commonName,
      options.recordedDate || new Date().toISOString().split("T")[0],
      options.latitude || "",
      options.longitude || "",
      options.recordedBy || "Lkotkote User",
      confidence,
      tek,
      "",
    ].join("\t");
  });

  return [header, ...rows].join("\n");
}

export async function exportDarwinCore(options: ExportOptions): Promise<void> {
  const zip = new JSZip();
  zip.file("meta.xml", buildMetaXml());
  zip.file("eml.xml", buildEmlXml(options));
  zip.file("occurrence.txt", buildOccurrenceTsv(options));

  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `lkotkote-dwc-a-${Date.now()}.zip`);
}

export function exportCSV(options: ExportOptions): void {
  const header = "occurrenceID,scientificName,vernacularName,confidence,startTime,endTime,latitude,longitude,tekAnnotation";
  const rows = options.detections.map((d) =>
    [
      d.id,
      `"${d.species}"`,
      `"${d.commonName}"`,
      d.confidence,
      d.startTime,
      d.endTime,
      options.latitude || "",
      options.longitude || "",
      `"${d.tekAnnotation || ""}"`,
    ].join(",")
  );
  const csv = [header, ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  saveAs(blob, `lkotkote-export-${Date.now()}.csv`);
}

export function exportJSON(options: ExportOptions): void {
  const data = {
    exportDate: new Date().toISOString(),
    platform: "Lkotkote",
    location: {
      latitude: options.latitude || null,
      longitude: options.longitude || null,
    },
    recordedDate: options.recordedDate || null,
    recordedBy: options.recordedBy || "Lkotkote User",
    detections: options.detections.map((d) => ({
      occurrenceID: d.id,
      basisOfRecord: "MachineObservation",
      scientificName: d.species,
      vernacularName: d.commonName,
      confidence: d.confidence,
      startTime: d.startTime,
      endTime: d.endTime,
      tekAnnotation: d.tekAnnotation || null,
    })),
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  saveAs(blob, `lkotkote-export-${Date.now()}.json`);
}
